#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
 
parser = argparse.ArgumentParser()
parser.add_argument("-v", "--verbose", help="Mostrar información", action="stor>
parser.add_argument("-f", "--file", help="Nombre de archivo a procesar")
args = parser.parse_args()
 
# Aquí procesamos lo que se tiene que hacer con cada argumento
if args.verbose:
    print("Version 0.0")
 
if args.file:
    print("El nombre de archivo a procesar es: ", args.file)
